#!/bin/bash
#part 2
wget http://factorized.net/crusoe.txt
find *txt
#grep "friday" crusoe.txt.1
grep -o -i "Friday" crusoe.txt.1 | wc -l
#sed -i "s/Friday/Saturday/gI" crusoe.txt | grep -o -i "Saturday" | wc -l
echo "hello world" >> crusoe.txt
echo "hello world" > crusoe.txt
touch quantity.txt
ls >> quantity.txt

#part 3
