#!/bin/bash
#part 2
wget http://factorized.net/crusoe.txt
find *txt
grep "friday" crusoe.txt
grep -o -i "Friday" crusoe.txt | wc -l
sed -i "s/Friday/Saturday/gI" crusoe.txt | grep -o -i "Saturday" | wc -w
echo "hello world" >> crusoe.txt
echo "hello world" > crusoe.txt
touch quantity.txt
ls >> quantity.txt

#part 3
