#!/bin/bash
#part 2
which cat
which less
which grep
which find
whereis cat
whereis less
whereis grep
whereis find
echo $PATH
touch rtr.sh
int main() {
    printf("Hello, World!");
    return 0;
}
chmod +x rtr.sh
gcc rtr.sh
export PATH = $PATH:/home/students/17205/zaitsev


#part 3
#!/bin/bash
touch file.txt
ls -l shared.txt
chmod 400 file.txt
ls file.txt
scp file.txt leonov@84.237.52.20:file.txt
